protoconf/__init__.py
protoconf/config.py
protoconf/schema.py
protoconf/types.py

Schema validation

---

configsuite/__init__.py
configsuite/config.py
configsuite/meta_keys.py
configsuite/schema.py
configsuite/types.py
configsuite/validation_errors.py
configsuite/validator.py
setup.py
tests/__init__.py
tests/test_element_validators.py
tests/test_keys.py
tests/test_license_header.py
tests/test_schema_validation.py
tests/test_types.py

Add license header to files

---

configsuite/__init__.py
configsuite/config.py
configsuite/meta_keys.py
configsuite/schema.py
configsuite/types.py
configsuite/validator.py
tests/test_dict.py
tests/test_element_validators.py
tests/test_keys.py
tests/test_schema_validation.py
tests/test_types.py

Implement non-named dicts

---

.gitignore
.travis.yml
configsuite/__about__.py
requirements.txt
setup.cfg
setup.py
tests/test_license_header.py

Pypi deploy

---

tests/test_user_types.py

Add test for user defined types

---

configsuite/__init__.py
configsuite/config.py
configsuite/validation_errors.py
configsuite/validator.py
tests/test_dict.py
tests/test_layers.py
tests/test_readable.py

Support merging configs

---

configsuite/__init__.py
configsuite/config.py
configsuite/meta_keys.py
configsuite/schema.py
configsuite/transformer.py
configsuite/types.py
configsuite/validation_errors.py
setup.py
tests/data/__init__.py
tests/data/numbers.py
tests/data/templating.py
tests/test_context_transformations.py
tests/test_layers.py
tests/test_layers_transformations.py
tests/test_transformations.py
tests/test_types.py

Transformations

---

.circleci/config.yml
requirements/circleci-docs-requirements.txt
requirements/circleci-requirements.txt
requirements/circleci-test-requirements.txt

Add circleci configuration

---

configsuite/types.py

Update _is_date validator message

---

configsuite/meta_keys.py
configsuite/schema.py
configsuite/validator.py
tests/data/advanced_store.py
tests/data/candy_bag.py
tests/data/computers.py
tests/test_allow_none.py

Add the option of allowing `None` as an accepted value in the configuration.

Allow None to be set as value

---

tests/test_context_element_validators.py

Fix typo in context validator test

---

configsuite/config.py
docs/source/conf.py
docs/source/index.rst
setup.cfg

Build documentation with warnings as errors

---

.flake8
configsuite/config.py
configsuite/docs/__init__.py
configsuite/schema.py
configsuite/types.py
requirements/ci-test-requirements.txt
setup.cfg
setup.py

Add flake8 to test suite to prevent codacy blockage as in: https://github.com/equinor/configsuite/pull/70

Add flake8 as part of tests

---

configsuite/config.py
configsuite/meta_keys.py
configsuite/schema.py
docs/source/user_guide/advanced.rst
docs/source/user_guide/getting_started.rst
setup.py
tests/data/__init__.py
tests/data/car.py
tests/test_default_values.py

Starting out with some tests.
Some of this is even pseudocode, so it's more to get a foundation for discussions how one would expect defaults to behave

Handle default values

---

README.md
docs/source/user_guide/getting_started.rst

Resolves #100 
Also resolves some of #99

Update docs allownone

---

.circleci/config.yml
.github/workflows/pythonpackage.yml
.travis.yml
requirements/ci-docs-requirements.txt
requirements/ci-requirements.txt
requirements/ci-test-requirements.txt
setup.py

Bump ci-requirements

---

configsuite/docs/__init__.py

This PR builds on #123 and is in the same spirit as #125 - only for the docs module instead.
The two last commits should be squashed before merged.

Docs deduce required

---

docs/source/release_notes.rst

Make dev release notes into 0.6 release notes. After this PR is merged I'll create the `0.6.0` tag.
Builds upon #134

Final preparations for releasing 0.6

---

configsuite/config.py
configsuite/types.py
tests/data/car.py
tests/test_layers.py
tests/test_readable.py
tests/test_types.py

Default containers to the empty container

---

docs/source/release_notes.rst

Prepare release notes for releasing the patches in #140 and #141

Add release notes 0.6.1

---

configsuite/extension/_static/configsuite_ext.css
configsuite/extension/ext_nodes.py

Fix sphinx extension breaking code formatting

---

docs/source/release_notes.rst

Update release notes in preparation for releasing 0.6.3

Release notes 0.6.3

---

configsuite/schema.py
docs/source/release_notes.rst
tests/test_schema_validation.py

Ensure that only collections can have content in schema

---

configsuite/meta_keys.py
configsuite/schema.py
configsuite/validator.py
docs/source/release_notes.rst
docs/source/user_guide/getting_started.rst
tests/test_basic_types.py
tests/test_containers.py

Resolves #149 
~~Note: We should probably merge #152 first...~~

Allow empty
